import type { ProductorApplicationForm } from '../types/productorApplication.types'

export const createDefaultProductorApplication = (user?: { name?: string; nombre?: string; email?: string }): ProductorApplicationForm => ({
  status: 'draft',
  personalInfo: {
    fullName: user?.name || user?.nombre || '',
    idType: 'nacional',
    identification: '',
    birthDate: '',
    phone: '',
    secondaryPhone: '',
    email: user?.email || '',
    province: '',
    canton: '',
    district: '',
    exactAddress: '',
  },
  agriculturalInfo: {
    producerType: 'directo',
    producesOwnProducts: true,
    farmName: '',
    farmAddress: '',
    farmSize: '',
    productionMethod: '',
    monthlyProduction: '',
    productCategories: [],
    mainProducts: '',
  },
  standInfo: {
    standName: '',
    description: '',
    fairId: '',
    requiresElectricity: false,
    requiresWater: false,
    scheduleNotes: '',
    socialMedia: '',
  },
  documentation: {
    hasMagRegistration: false,
    magRegistrationNumber: '',
    magIssueDate: '',
    magExpiryDate: '',
    documents: [],
  },
  sanitaryInfo: {
    hasFoodHandlerCard: false,
    foodHandlerCardNumber: '',
    foodHandlerIssueDate: '',
    foodHandlerExpiryDate: '',
    healthPermitNumber: '',
    senasaRegistration: '',
    coldChainRequired: false,
    coldChainDescription: '',
  },
  taxInfo: {
    regime: 'no_inscrito',
    taxNumber: '',
  },
  confirmation: {
    swornDeclaration: false,
    adminReviewRequired: false,
    observations: '',
  },
})
